name = "url-monitor-service"
main = "src/index.ts"
compatibility_date = "2024-03-12"
compatibility_flags = ["nodejs_compat"]

workers_dev = true  # Move this here

[vars]
JWT_SECRET = "7f45a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9"
DATABASE_URL = "postgresql://neondb_owner:npg_q1wNCWSjkhV6@ep-divine-silence-a4c8q69p-pooler.us-east-1.aws.neon.tech/bizgurukul?sslmode=require"

[triggers]
crons = ["*/5 * * * *"]  # Run every 5 minutes

[dev]
port = 8787

[env.production]
name = "url-monitor-service"
main = "src/index.ts"
compatibility_date = "2024-03-12"
compatibility_flags = ["nodejs_compat"]

[env.production.vars]
JWT_SECRET = "7f45a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b3c4d5e6f7a8b9"
DATABASE_URL = "postgresql://neondb_owner:npg_q1wNCWSjkhV6@ep-divine-silence-a4c8q69p-pooler.us-east-1.aws.neon.tech/bizgurukul?sslmode=require"

[env.production.triggers]
crons = ["*/5 * * * *"]  # Run every 5 minutes
